global using AutoHook.Actions;
global using AutoHook.Data;
global using AutoHook.Enums;
global using AutoHook.Modules;
global using AutoHook.Modules.Gig;
global using AutoHook.Modules.Ocean;
global using AutoHook.Modules.Rod;
global using AutoHook.Presets;
global using AutoHook.Presets.AutoCasts;
global using AutoHook.Presets.Bases;
global using AutoHook.Presets.Config;
global using AutoHook.Presets.Migration;
global using AutoHook.Presets.Migration.Legacy;
global using AutoHook.Conditions;
global using AutoHook.Conditions.Bases;
global using AutoHook.Conditions.Definitions;
global using AutoHook.Conditions.Model;
global using AutoHook.Conditions.Params;
global using Condition = AutoHook.Conditions.Model.Condition;
global using static AutoHook.Conditions.Params.ConditionParams;
global using static AutoHook.Conditions.ConditionRegistry;
global using AutoHook.Resources.Localization;
global using AutoHook.Ui;
global using AutoHook.Utils;
global using AutoHook.World;
global using AutoHook.World.State;
global using AutoHook.World.UpdateModules;
global using GamePlayerState = FFXIVClientStructs.FFXIV.Client.Game.UI.PlayerState;
global using Dalamud.Plugin.Services;
global using clib.Extensions;
global using clib.Services;
global using ECommons;
global using ECommons.GameHelpers;
global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Text;
global using System.Threading.Tasks;
global using static ECommons.GenericHelpers;
